
#ifndef __SOFTWAREANDSERVICES_LIBRARY_IETF_ABNF_GENERATE_CPLUSPLUS_HPP__
#define __SOFTWAREANDSERVICES_LIBRARY_IETF_ABNF_GENERATE_CPLUSPLUS_HPP__

#include "Generate.hpp"

/**
 * Generate C++ onbjects and code.
 */
extern int		GenerateCPlusPlus();

#endif // __SOFTWAREANDSERVICES_LIBRARY_IETF_ABNF_GENERATE_CPLUSPLUS_HPP__
